name: p2plib
description: 'Tooling for encrypted udp datagram peer to peer communication'
version: 2.2.0
homepage: https://github.com/alexandrim0/p2plib-dart

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies: 
  collection: ^1.17.0
  sodium: ^2.3.0
  meta: ^1.10.0

dev_dependencies:
  very_good_analysis: ^5.1.0
  test: ^1.24.3
